from rest_framework import serializers
from media.models import Media


# Serializers to convert data to JSON format
# Unique Id is generated by Serializers for every POST request

class MediaSerializer(serializers.ModelSerializer):
    class Meta:
        model = Media
        fields = ('id',
                  'name',
                  'media_type',
                  'create_datetime',
                  'update_datetime'
                  )
