# Generated by Django 3.2.4 on 2021-06-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    #

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('media_type', models.CharField(default='', max_length=50)),
                ('create_datetime', models.BooleanField(default=False)),
                ('update_datetime', models.DateTimeField(default=False)),
            ],
        ),
    ]
