# Generated by Django 3.2.4 on 2021-06-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_create_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='update_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
